runtime: custom
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 90
  cpu_utilization:
    target_utilization: 0.65

handlers:
  - url: /.*
    script: auto

health_check:
  enable_health_check: true
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
